export interface Technology {
    id: string
    name: string
    sector: string
    trendCluster: string
    focusArea: string
    impact: number // 0-100
    timeline: number // years
    department: string
    supplyChainStage: string
    tradeChannelType: string
    industry: string
    description: string
    x?: number // for chart positioning
    y?: number // for chart positioning
}
export const menuItems = [
    {
        key: 'parent1',
        title: 'والد ۱',
        checked: false, // checked اولیه
        children: [
            {
                key: 'child1-1',
                title: 'فرزند ۱-۱',
                checked: false
            },
            {
                key: 'child1-2',
                title: 'فرزند ۱-۲',
                checked:false,
            },
        ],
    },{
        key: 'parent2',
        title: 'والد2',
        checked: false, // checked اولیه
        children: [
            {
                key: 'child1-1',
                title: 'فرزند ۱-۱',
                checked: false
            },
            {
                key: 'child1-2',
                title: 'فرزند ۱-۲',
                checked:false,
            },
        ],
    },

];
export interface FilterState {
    sectors: string[]
    trendClusters: string[]
    focusAreas: string[]
    departments: string[]
    supplyChainStages: string[]
    tradeChannelTypes: string[]
    industries: string[]
}

export const mockTechnologies: Technology[] = [
    {
        id: "1",
        name: "Audio AI",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Customer Experience",
        impact: 75,
        timeline: 2,
        department: "IT Support",
        supplyChainStage: "Last‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Retail – Online & Offline",
        description: "AI-powered audio processing and voice recognition technologies for enhanced customer interactions.",
    },
    {
        id: "2",
        name: "Gen AI",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Automation & Efficiency",
        impact: 95,
        timeline: 3,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description:
            "Generative artificial intelligence for content creation, code generation, and automated decision making.",
    },
    {
        id: "3",
        name: "AI Chatbots",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Customer Experience",
        impact: 85,
        timeline: 1,
        department: "Customer Service",
        supplyChainStage: "Last‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Retail – Online & Offline",
        description: "Intelligent conversational agents for customer support and automated assistance.",
    },
    {
        id: "4",
        name: "Digital Twins",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Visibility & Resilience",
        impact: 80,
        timeline: 4,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Virtual replicas of physical systems for real-time monitoring and optimization.",
    },
    {
        id: "5",
        name: "Advanced Analytics",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Automation & Efficiency",
        impact: 90,
        timeline: 2,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Sophisticated data analysis tools for predictive insights and business intelligence.",
    },
    {
        id: "6",
        name: "Next Generation Packaging",
        sector: "Technology",
        trendCluster: "Renewable Energy",
        focusArea: "Sustainability",
        impact: 60,
        timeline: 3,
        department: "Warehouse Operations",
        supplyChainStage: "Last‑Mile Logistics",
        tradeChannelType: "Direct‑to‑Consumer (D2C) Model",
        industry: "Food & Beverage",
        description: "Sustainable and smart packaging solutions with embedded sensors and eco-friendly materials.",
    },
    {
        id: "7",
        name: "Computer Vision",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Automation & Efficiency",
        impact: 85,
        timeline: 2,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "AI-powered visual recognition and analysis for quality control and automation.",
    },
    {
        id: "8",
        name: "IoT (Internet of Things)",
        sector: "Technology",
        trendCluster: "IoT",
        focusArea: "Automation & Efficiency",
        impact: 80,
        timeline: 2,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Retail – Online & Offline",
        description: "Connected devices and sensors for real-time monitoring and data collection.",
    },
    {
        id: "9",
        name: "Blockchain",
        sector: "Technology",
        trendCluster: "Blockchain",
        focusArea: "Visibility & Resilience",
        impact: 70,
        timeline: 5,
        department: "Warehouse Operations",
        supplyChainStage: "First‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Distributed ledger technology for transparent and secure transactions.",
    },
    {
        id: "10",
        name: "RFID Technology",
        sector: "Technology",
        trendCluster: "IoT",
        focusArea: "Visibility & Resilience",
        impact: 65,
        timeline: 1,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Retail – Online & Offline",
        description: "Radio frequency identification for inventory tracking and asset management.",
    },
    {
        id: "11",
        name: "Extended Reality (AR+VR+MR)",
        sector: "Technology",
        trendCluster: "Mixed Reality (AR/VR/MR)",
        focusArea: "Customer Experience",
        impact: 75,
        timeline: 4,
        department: "Customer Service",
        supplyChainStage: "Last‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Retail – Online & Offline",
        description: "Immersive technologies combining augmented, virtual, and mixed reality experiences.",
    },
    {
        id: "12",
        name: "Robots (Mobile & Stationary)",
        sector: "Technology",
        trendCluster: "Robotics & Automation",
        focusArea: "Automation & Efficiency",
        impact: 85,
        timeline: 3,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Automated robotic systems for manufacturing, warehousing, and logistics operations.",
    },
    {
        id: "13",
        name: "Next Generation Connectivity (5G & 6G)",
        sector: "Technology",
        trendCluster: "Communications (5G/6G)",
        focusArea: "Automation & Efficiency",
        impact: 90,
        timeline: 4,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Mobile Commerce (M‑commerce)",
        industry: "Energy & Infrastructure",
        description: "Ultra-fast, low-latency wireless networks enabling advanced IoT and mobile applications.",
    },
    {
        id: "14",
        name: "Remote Operations",
        sector: "Technology",
        trendCluster: "Communications (5G/6G)",
        focusArea: "Health, Safety & Future of Work",
        impact: 70,
        timeline: 2,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Technologies enabling remote monitoring and control of industrial operations.",
    },
    {
        id: "15",
        name: "Geographic Information Systems (GIS)",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Visibility & Resilience",
        impact: 65,
        timeline: 3,
        department: "Transportation",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Mobility, Smart City & Logistics Infra",
        description: "Spatial data analysis and mapping systems for location-based decision making.",
    },
    {
        id: "16",
        name: "Wearable Devices/Sensors",
        sector: "Technology",
        trendCluster: "IoT",
        focusArea: "Health, Safety & Future of Work",
        impact: 70,
        timeline: 2,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Direct‑to‑Consumer (D2C) Model",
        industry: "Healthcare, Pharma & Care",
        description: "Wearable technology for health monitoring and workplace safety enhancement.",
    },
    {
        id: "17",
        name: "Edge Computing",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Automation & Efficiency",
        impact: 80,
        timeline: 3,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Distributed computing bringing data processing closer to the source of data generation.",
    },
    {
        id: "18",
        name: "Smart Printables",
        sector: "Technology",
        trendCluster: "IoT",
        focusArea: "Automation & Efficiency",
        impact: 55,
        timeline: 5,
        department: "Warehouse Operations",
        supplyChainStage: "Last‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Intelligent printed materials with embedded sensors and communication capabilities.",
    },
    {
        id: "19",
        name: "Sensors",
        sector: "Technology",
        trendCluster: "IoT",
        focusArea: "Visibility & Resilience",
        impact: 75,
        timeline: 1,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Advanced sensing technologies for environmental monitoring and data collection.",
    },
    {
        id: "20",
        name: "Biometric Systems",
        sector: "Technology",
        trendCluster: "AI",
        focusArea: "Physical & Digital Security",
        impact: 70,
        timeline: 2,
        department: "IT Support",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Healthcare, Pharma & Care",
        description: "Identity verification systems using biological characteristics for security and access control.",
    },
    {
        id: "21",
        name: "Exoskeletons",
        sector: "Technology",
        trendCluster: "Robotics & Automation",
        focusArea: "Health, Safety & Future of Work",
        impact: 60,
        timeline: 6,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Manufacturing & Industrial Goods",
        description: "Wearable robotic systems to enhance human strength and reduce workplace injuries.",
    },
    {
        id: "22",
        name: "Renewable Energy",
        sector: "Energy",
        trendCluster: "Renewable Energy",
        focusArea: "Sustainability",
        impact: 85,
        timeline: 5,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Energy & Infrastructure",
        description: "Clean energy technologies including solar, wind, and advanced battery storage systems.",
    },
    {
        id: "23",
        name: "Drones",
        sector: "Technology",
        trendCluster: "Autonomous Transportation and Drones",
        focusArea: "Automation & Efficiency",
        impact: 75,
        timeline: 4,
        department: "Transportation",
        supplyChainStage: "Last‑Mile Logistics",
        tradeChannelType: "Fast Commerce",
        industry: "Mobility, Smart City & Logistics Infra",
        description: "Unmanned aerial vehicles for delivery, surveillance, and inspection applications.",
    },
    {
        id: "24",
        name: "3D Printing",
        sector: "Technology",
        trendCluster: "Robotics & Automation",
        focusArea: "Automation & Efficiency",
        impact: 70,
        timeline: 3,
        department: "Warehouse Operations",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Direct‑to‑Consumer (D2C) Model",
        industry: "Manufacturing & Industrial Goods",
        description: "Additive manufacturing technology for on-demand production and rapid prototyping.",
    },
    {
        id: "25",
        name: "Autonomous Vehicles",
        sector: "Technology",
        trendCluster: "Autonomous Transportation and Drones",
        focusArea: "Automation & Efficiency",
        impact: 90,
        timeline: 8,
        department: "Transportation",
        supplyChainStage: "Mid‑Mile Logistics",
        tradeChannelType: "Electronic Commerce (E‑commerce)",
        industry: "Mobility, Smart City & Logistics Infra",
        description: "Self-driving vehicles for transportation and logistics with advanced AI navigation systems.",
    },
]